site_name: EECS NOOB
theme: 
  # The overall theme
  name: material

  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  

  # Color Theme
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: cyan     # Header Color
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to light mode

plugins:
  - blog
  - tags

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MorrisHohoho
  

copyright: Copyright &copy; 2023 Ruoshen Mo

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

