
# Site 
site_name: 赢
site_author: MorrisHohoho
repo_name: NOOB_BLOGS
repo_url: https://github.com/MorrisHohoho/NOOB_BLOGS
copyright: Copyright &copy; 2023 Ruoshen Mo

# nav:
#   - Home:
#     - About: index.md
#   - Notes:
#     - About: notes/index.md
#     - CS: notes/CS/



theme: 
  # The overall theme
  name: material

  #The site logo(header)
  icon:
    logo: material/school
    repo: fontawesome/brands/github

  features:
    # - header.autohide

    - content.tabs.link
    - content.code.annotation
    - content.code.copy

    - navigation.tabs
    - navigation.expansion
    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    # - navigation.path

    # - toc.integrate
    - toc.follow

    - search.suggest
    - search.highlight

    - announce.dismiss

  # Color Theme
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: cyan     # Header Color
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to light mode

  


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized
  # - tags:
  #     tags_file: cases/tags.md


extra:
  analytics:
    provider: google
    property: G-33KRCT3PJL

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MorrisHohoho
    - icon: fontawesome/solid/paper-plane
      link: mailto:morrishohoho@gmail.com